(() => {
const C=window.NEXORA_CONFIG;if(!C||!window.supabase)return;const db=window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_KEY);const $=id=>document.getElementById(id);const msg=(id,t,bad=false)=>{const e=$(id);if(e){e.textContent=t;e.style.color=bad?'#ff6b7a':'#20e6ff'}};
async function session(){const {data}=await db.auth.getSession();return data.session}
function authPage(){if(!$('loginForm'))return;$('loginTab').onclick=()=>{location.hash='login';toggleAuth()};$('registerTab').onclick=()=>{location.hash='register';toggleAuth()};function toggleAuth(){const r=location.hash==='#register';$('loginForm').classList.toggle('hidden',r);$('registerForm').classList.toggle('hidden',!r);$('loginTab').classList.toggle('active',!r);$('registerTab').classList.toggle('active',r)}toggleAuth();$('loginForm').onsubmit=async e=>{e.preventDefault();msg('authMsg','Đang đăng nhập...');const {error}=await db.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)return msg('authMsg',error.message,true);location.href='dashboard.html'};$('registerForm').onsubmit=async e=>{e.preventDefault();msg('authMsg','Đang tạo tài khoản...');const {error}=await db.auth.signUp({email:$('registerEmail').value.trim(),password:$('registerPassword').value,options:{data:{display_name:$('registerName').value.trim()}}});if(error)return msg('authMsg',error.message,true);msg('authMsg','Đăng ký thành công. Nếu Supabase yêu cầu xác minh email, hãy kiểm tra hộp thư.');};}
async function requireUser(){const s=await session();if(!s){location.href='auth.html';return null}return s.user}
async function logoutSetup(){if($('logoutBtn'))$('logoutBtn').onclick=async()=>{await db.auth.signOut();location.href='index.html'}}
let currentChallenge=null,myProfile=null;
async function dashboard(){if(!$('profileForm'))return;const user=await requireUser();if(!user)return;logoutSetup();const {data:p,error}=await db.from('nexora_profiles').select('*').eq('user_id',user.id).single();if(error)return msg('dashMsg','Hãy chạy file SQL v1.0 trong Supabase trước.',true);myProfile=p;$('displayName').value=p.display_name||'';$('gameUid').value=p.game_uid||'';$('gameRank').value=p.game_rank||'Chưa cập nhật';$('helloName').textContent=p.display_name||'Game thủ';$('navName').textContent=p.display_name||'';$('myPoints').textContent=p.points||0;if(p.role==='admin')$('adminLink').classList.remove('hidden');drawCard();loadLeaderboard();loadEvents(user);loadDaily(user);if($('refreshEvents'))$('refreshEvents').onclick=()=>loadEvents(user);if($('refreshDaily'))$('refreshDaily').onclick=()=>loadDaily(user);$('profileForm').onsubmit=async e=>{e.preventDefault();const upd={display_name:$('displayName').value.trim(),game_uid:$('gameUid').value.trim()||null,game_rank:$('gameRank').value};const {error}=await db.from('nexora_profiles').update(upd).eq('user_id',user.id);if(error)return msg('dashMsg',error.message,true);Object.assign(myProfile,upd);$('helloName').textContent=upd.display_name;$('navName').textContent=upd.display_name;drawCard();msg('dashMsg','Đã lưu hồ sơ ✓')};$('randomBtn').onclick=async()=>{const {data,error}=await db.from('nexora_challenges').select('*').eq('is_active',true);if(error||!data?.length)return msg('dashMsg','Chưa có challenge. Hãy chạy SQL seed hoặc thêm từ Admin.',true);currentChallenge=data[Math.floor(Math.random()*data.length)];$('challengeBox').innerHTML=`<b>${esc(currentChallenge.title)}</b><br><span>${esc(currentChallenge.description)}</span><br><small>+${currentChallenge.points} điểm</small>`;$('completeBtn').disabled=false};$('completeBtn').onclick=async()=>{if(!currentChallenge)return;const {data,error}=await db.rpc('nexora_complete_challenge',{p_challenge_id:currentChallenge.id});if(error)return msg('dashMsg',error.message,true);msg('dashMsg',data?.message||'Đã ghi nhận ✓',!data?.ok);if(data?.ok){myProfile.points=data.points;$('myPoints').textContent=data.points;drawCard();loadLeaderboard()}$('completeBtn').disabled=true};$('downloadCard').onclick=()=>{const a=document.createElement('a');a.download='nexora-player-card.png';a.href=$('playerCard').toDataURL('image/png');a.click()};}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadLeaderboard(){const {data}=await db.from('nexora_profiles').select('display_name,game_rank,points').order('points',{ascending:false}).limit(10);$('leaderboard').innerHTML=(data||[]).map((x,i)=>`<div class="row"><span>#${i+1}</span><span>${esc(x.display_name||'Game thủ')}<small> • ${esc(x.game_rank||'')}</small></span><strong>${x.points}</strong></div>`).join('')||'Chưa có dữ liệu.'}
function drawCard(){const c=$('playerCard');if(!c||!myProfile)return;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,720,400);g.addColorStop(0,'#07101d');g.addColorStop(1,'#123a5a');x.fillStyle=g;x.fillRect(0,0,720,400);x.strokeStyle='#20e6ff';x.lineWidth=3;x.strokeRect(18,18,684,364);x.fillStyle='#20e6ff';x.font='900 30px sans-serif';x.fillText('NEXORA GAMING',45,70);x.fillStyle='#fff';x.font='900 48px sans-serif';x.fillText((myProfile.display_name||'GAME THỦ').slice(0,20),45,155);x.fillStyle='#9fb5cf';x.font='24px sans-serif';x.fillText('UID: '+(myProfile.game_uid||'Chưa cập nhật'),45,210);x.fillText('Rank: '+(myProfile.game_rank||'Chưa cập nhật'),45,250);x.fillStyle='#ffd84a';x.font='900 44px sans-serif';x.fillText((myProfile.points||0)+' PTS',45,325);x.fillStyle='#6ee7f7';x.font='18px sans-serif';x.fillText('PLAYER CARD • COMMUNITY EDITION',405,345)}
async function admin(){if(!$('challengeForm'))return;const user=await requireUser();if(!user)return;logoutSetup();const {data:p}=await db.from('nexora_profiles').select('role').eq('user_id',user.id).single();if(p?.role!=='admin'){location.href='dashboard.html';return}async function load(){const [u,c,l]=await Promise.all([db.from('nexora_profiles').select('*',{count:'exact',head:true}),db.from('nexora_challenges').select('*',{count:'exact',head:true}),db.from('nexora_challenge_completions').select('*',{count:'exact',head:true})]);$('adminUsers').textContent=u.count||0;$('adminChallenges').textContent=c.count||0;$('adminCompletions').textContent=l.count||0;const {data}=await db.from('nexora_challenges').select('*').order('created_at',{ascending:false});$('adminChallengeList').innerHTML=(data||[]).map(x=>`<div class="admin-item"><span><b>${esc(x.title)}</b><br><small>${esc(x.description)} • ${x.points} điểm</small></span><button class="ghost toggle" data-id="${x.id}" data-active="${x.is_active}">${x.is_active?'Tắt':'Bật'}</button></div>`).join('');document.querySelectorAll('.toggle').forEach(b=>b.onclick=async()=>{await db.from('nexora_challenges').update({is_active:b.dataset.active!=='true'}).eq('id',b.dataset.id);load()})}await load();$('challengeForm').onsubmit=async e=>{e.preventDefault();const {error}=await db.from('nexora_challenges').insert({title:$('challengeTitle').value.trim(),description:$('challengeDescription').value.trim(),points:+$('challengePoints').value});if(error)return msg('adminMsg',error.message,true);e.target.reset();$('challengePoints').value=10;msg('adminMsg','Đã thêm challenge ✓');load()}}
async function loadEvents(user){
 const box=$('eventList'), mine=$('myEntries'); if(!box)return;
 const {data:events,error}=await db.from('nexora_events').select('*').eq('is_published',true).order('starts_at',{ascending:false});
 if(error){box.textContent='Hãy chạy SQL v1.2 trước.';return}
 const {data:entries}=await db.from('nexora_event_entries').select('event_id,status,created_at').eq('user_id',user.id);
 const map=new Map((entries||[]).map(x=>[x.event_id,x])); const now=Date.now();
 box.innerHTML=(events||[]).map(e=>{const joined=map.has(e.id), open=now>=new Date(e.starts_at).getTime()&&now<=new Date(e.ends_at).getTime();return `<article class="event-card"><div class="event-meta"><span class="pill">${open?'ĐANG DIỄN RA':'EVENT'}</span><span class="pill reward">🎁 ${esc(e.reward_text)}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="event-rules"><b>Thể lệ:</b> ${esc(e.rules)}</div><p class="note">${fmtDate(e.starts_at)} → ${fmtDate(e.ends_at)}</p><button class="${joined?'ghost':'btn'} join-event" data-id="${e.id}" ${joined||!open?'disabled':''}>${joined?'✓ Đã tham gia':open?'Tham gia miễn phí':'Chưa mở / Đã kết thúc'}</button></article>`}).join('')||'<div class="coming">CHƯA CÓ EVENT <small>Admin chưa công bố sự kiện mới.</small></div>';
 document.querySelectorAll('.join-event').forEach(b=>b.onclick=async()=>{const {data,error}=await db.rpc('nexora_join_event',{p_event_id:b.dataset.id});if(error)return msg('dashMsg',error.message,true);msg('dashMsg',data?.message||'Đã tham gia',!data?.ok);loadEvents(user)});
 if(mine)mine.innerHTML=(events||[]).filter(e=>map.has(e.id)).map(e=>{const x=map.get(e.id);return `<div class="entry"><b>${esc(e.title)}</b> • <span class="entry-status">${statusText(x.status)}</span><br><small>Phần thưởng: ${esc(e.reward_text)} • Tham gia ${fmtDate(x.created_at)}</small></div>`}).join('')||'Bạn chưa tham gia Event nào.';
}
function fmtDate(v){try{return new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v||''}}
function statusText(s){return ({joined:'Đã tham gia',verified:'Đã xác minh',winner:'Nhận thưởng',not_selected:'Không được chọn',rewarded:'Đã trao thưởng'})[s]||s}
async function loadDaily(user){
 const box=$('dailyList');if(!box)return;
 const [tasks,summary,badges]=await Promise.all([db.rpc('nexora_daily_challenges'),db.rpc('nexora_my_daily_summary'),db.rpc('nexora_my_achievements')]);
 if(tasks.error){box.textContent='Hãy chạy SQL v1.3 trước.';return}
 const sum=summary.data||{};$('dailyStreak').textContent=sum.streak||0;$('dailyDone').textContent=(sum.today_done||0)+'/3';$('weeklyPoints').textContent=sum.weekly_points||0;$('weeklyRank').textContent=sum.weekly_rank?'#'+sum.weekly_rank:'—';
 box.innerHTML=(tasks.data||[]).map(x=>`<article class="daily-card ${x.completed?'done':''}"><span class="difficulty ${x.difficulty}">${x.difficulty==='easy'?'DỄ':x.difficulty==='medium'?'VỪA':'KHÓ'}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><b>+${x.points} điểm</b><br><button class="${x.completed?'ghost':'btn'} daily-complete" data-id="${x.id}" ${x.completed?'disabled':''}>${x.completed?'✓ Đã hoàn thành':'Hoàn thành'}</button></article>`).join('')||'Chưa đủ Challenge hoạt động.';
 document.querySelectorAll('.daily-complete').forEach(b=>b.onclick=async()=>{const {data,error}=await db.rpc('nexora_complete_daily_challenge',{p_challenge_id:b.dataset.id});if(error)return msg('dashMsg',error.message,true);msg('dashMsg',data?.message||'Đã hoàn thành',!data?.ok);if(data?.ok){myProfile.points=data.points;$('myPoints').textContent=data.points;drawCard();loadLeaderboard()}loadDaily(user)});
 const ab=$('achievementList');if(ab)ab.innerHTML=(badges.data||[]).map(a=>`<div class="badge ${a.unlocked?'':'locked'}"><b>${a.icon} ${esc(a.title)}</b><small>${esc(a.description)}</small><br><span>${a.unlocked?'✓ Đã mở khóa':'🔒 Chưa mở'}</span></div>`).join('');
}
async function adminEvents(){
 if(!$('eventForm'))return;
 async function load(){const {data}=await db.from('nexora_events').select('*,nexora_event_entries(count)').order('created_at',{ascending:false});$('adminEvents').textContent=(data||[]).length;$('adminEventList').innerHTML=(data||[]).map(e=>`<div class="admin-event"><b>${esc(e.title)}</b> <span class="pill reward">${esc(e.reward_text)}</span><br><small>${fmtDate(e.starts_at)} → ${fmtDate(e.ends_at)} • ${(e.nexora_event_entries?.[0]?.count||0)} người tham gia • ${e.is_published?'Đang công bố':'Đang ẩn'}</small><div class="admin-event-actions"><button class="ghost ev-toggle" data-id="${e.id}" data-v="${e.is_published}">${e.is_published?'Ẩn':'Công bố'}</button><button class="ghost ev-entries" data-id="${e.id}">Người tham gia</button></div></div>`).join('')||'Chưa có Event.';document.querySelectorAll('.ev-toggle').forEach(b=>b.onclick=async()=>{await db.from('nexora_events').update({is_published:b.dataset.v!=='true'}).eq('id',b.dataset.id);load()});document.querySelectorAll('.ev-entries').forEach(b=>b.onclick=()=>loadEntries(b.dataset.id))}
 async function loadEntries(id){const {data,error}=await db.rpc('nexora_admin_event_entries',{p_event_id:id});if(error)return msg('adminMsg',error.message,true);$('adminEntryList').innerHTML=(data||[]).map(x=>`<div class="entry"><b>${esc(x.display_name)}</b> <small>${esc(x.game_uid||'UID chưa cập nhật')}</small><br><span class="entry-status">${statusText(x.status)}</span> • <small>${fmtDate(x.joined_at)}</small><div class="admin-event-actions"><button class="ghost entry-status-btn" data-entry="${x.entry_id}" data-status="verified">Xác minh</button><button class="ghost entry-status-btn" data-entry="${x.entry_id}" data-status="winner">Chọn nhận thưởng</button><button class="ghost entry-status-btn" data-entry="${x.entry_id}" data-status="rewarded">Đã trao</button></div></div>`).join('')||'Chưa có người tham gia.';document.querySelectorAll('.entry-status-btn').forEach(b=>b.onclick=async()=>{const {error}=await db.rpc('nexora_admin_set_entry_status',{p_entry_id:b.dataset.entry,p_status:b.dataset.status});if(error)return msg('adminMsg',error.message,true);loadEntries(id)})}
 $('eventForm').onsubmit=async e=>{e.preventDefault();const row={title:$('eventTitle').value.trim(),description:$('eventDescription').value.trim(),reward_text:$('eventReward').value.trim(),rules:$('eventRules').value.trim(),starts_at:new Date($('eventStart').value).toISOString(),ends_at:new Date($('eventEnd').value).toISOString(),is_published:true};if(new Date(row.ends_at)<=new Date(row.starts_at))return msg('adminMsg','Thời gian kết thúc phải sau thời gian bắt đầu.',true);const {error}=await db.from('nexora_events').insert(row);if(error)return msg('adminMsg',error.message,true);e.target.reset();msg('adminMsg','Đã tạo và công bố Event ✓');load()}; await load();
}

authPage();dashboard();admin();adminEvents();
})();
