(() => {
const $=id=>document.getElementById(id), safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const db=window.NEXORA_DB;if(!db)return;let user=null,profile=null,events=[],entryMap=new Map(),countMap=new Map(),resultMap=new Map(),filter='all',ticker=null;
const say=(t,bad=false)=>{const e=$('eventCenterMsg');if(e){e.textContent=t||'';e.classList.toggle('bad',bad)}};
const fmt=v=>{try{return new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v||''}};
const state=e=>{if(e.lifecycle_status==='ended'||Date.now()>new Date(e.ends_at).getTime())return'ended';if(Date.now()<new Date(e.starts_at).getTime())return'upcoming';return'live'};
const stateLabel=s=>s==='live'?'● LIVE':s==='upcoming'?'SẮP DIỄN RA':'ĐÃ KẾT THÚC';
const statusText=s=>({joined:'Đã tham gia',verified:'Đã xác minh',winner:'Người thắng',not_selected:'Không được chọn',rewarded:'Đã trao thưởng'})[s]||s||'—';
async function rpc(name,args={}){const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data}
async function auth(){const {data:{session}}=await db.auth.getSession();if(!session){location.href='auth.html';return false}user=session.user;const r=await db.from('nexora_profiles').select('*').eq('user_id',user.id).maybeSingle();profile=r.data||{};if(profile.is_suspended){await db.auth.signOut();location.href='auth.html';return false}if($('hubUser'))$('hubUser').textContent=profile.display_name||user.email||'Game thủ';if(profile.role==='admin')$('hubAdmin')?.classList.remove('hidden');$('hubLogout')?.addEventListener('click',async()=>{await db.auth.signOut();location.href='index.html'});return true}
function countdownText(end){let d=new Date(end).getTime()-Date.now();if(d<=0)return'Đã đến thời điểm';const days=Math.floor(d/86400000);d%=86400000;const h=Math.floor(d/3600000);d%=3600000;const m=Math.floor(d/60000);const s=Math.floor((d%60000)/1000);return`${days?days+' ngày ':''}${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function startTicker(){clearInterval(ticker);const tick=()=>document.querySelectorAll('[data-event-countdown]').forEach(el=>{el.textContent=countdownText(el.dataset.eventCountdown);if(new Date(el.dataset.eventCountdown)<=new Date())el.classList.add('ended')});tick();ticker=setInterval(tick,1000)}
function participantText(e){const n=Number(countMap.get(String(e.id))||0);return e.max_participants?`${n}/${e.max_participants} người`:`${n} người tham gia`}
function progress(e){if(!e.max_participants)return'';const n=Number(countMap.get(String(e.id))||0),pct=Math.min(100,Math.round(n/Number(e.max_participants)*100));return`<div class="event-progress"><i style="width:${pct}%"></i></div><small>${participantText(e)}</small>`}
function resultHtml(e){const rows=resultMap.get(String(e.id))||[];if(!e.result_text&&!rows.length)return'';return`<div class="event-result-box"><b>🏆 Kết quả Event</b>${e.result_text?`<p>${safe(e.result_text)}</p>`:''}${rows.length?`<div class="event-winner-list">${rows.map((x,i)=>`<div class="event-winner"><span>${i===0?'🥇':'🏅'} ${safe(x.display_name)}</span><b>${safe(statusText(x.status))}</b></div>`).join('')}</div>`:''}</div>`}
function card(e){const st=state(e),joined=entryMap.has(String(e.id)),n=Number(countMap.get(String(e.id))||0),full=e.max_participants&&n>=Number(e.max_participants),can=st==='live'&&!joined&&!full&&e.lifecycle_status==='published';const target=st==='upcoming'?e.starts_at:e.ends_at;return`<article class="event-card-v272 ${e.is_featured?'featured':''}" data-state="${st}"><div class="event-card-meta"><span class="event-state ${st}">${stateLabel(st)}</span>${e.is_featured?'<span class="hub-badge">⭐ FEATURED</span>':''}<span class="grow">${participantText(e)}</span></div><h3>${safe(e.title)}</h3><p>${safe(e.description||'')}</p><div class="hub-badge">🎁 ${safe(e.reward_text||'Phần thưởng cộng đồng')}</div><div class="event-countdown ${st==='ended'?'ended':''}" data-event-countdown="${target}">${st==='ended'?'Đã kết thúc':'Đang tính...'}</div>${progress(e)}${resultHtml(e)}<div class="hub-card-actions"><a class="ghost" href="event.html?id=${encodeURIComponent(e.id)}">Xem chi tiết</a><button class="${joined?'ghost':'btn'} join-event-v272" data-id="${e.id}" ${can?'':'disabled'}>${joined?'✓ Đã tham gia':full?'Đã đủ người':st==='upcoming'?'Chưa mở':st==='ended'?'Đã kết thúc':'Tham gia miễn phí'}</button></div></article>`}
function visibleEvents(){return events.filter(e=>filter==='all'||state(e)===filter||filter==='mine'&&entryMap.has(String(e.id)))}
function render(){const box=$('eventListV272');if(!box)return;const rows=visibleEvents();box.innerHTML=rows.map(card).join('')||'<div class="hub-empty">Không có Event trong mục này.</div>';box.querySelectorAll('.join-event-v272').forEach(b=>b.onclick=()=>join(b));renderFeatured();renderHistory();startTicker()}
function renderFeatured(){const box=$('eventFeatured');if(!box)return;const e=events.find(x=>x.is_featured&&state(x)!=='ended')||events.find(x=>state(x)==='live')||events.find(x=>state(x)==='upcoming');if(!e){box.classList.remove('has-banner');box.innerHTML='<div class="event-featured-empty"><div class="hub-kicker">FEATURED EVENT</div><h2>Chưa có Event nổi bật</h2><p>Admin chưa chọn Event Featured.</p></div>';return}if(e.banner_url){box.classList.add('has-banner');box.style.backgroundImage=`linear-gradient(90deg,rgba(5,7,10,.95),rgba(5,7,10,.66),rgba(5,7,10,.25)),url("${String(e.banner_url).replace(/["\\]/g,'')}")`}else{box.classList.remove('has-banner');box.style.backgroundImage=''}const st=state(e),joined=entryMap.has(String(e.id));box.innerHTML=`<div class="hub-kicker">⭐ FEATURED EVENT • ${stateLabel(st)}</div><h2>${safe(e.title)}</h2><p>${safe(e.description||'')}</p><div class="hub-badge">🎁 ${safe(e.reward_text||'Phần thưởng cộng đồng')}</div><div class="event-countdown ${st==='ended'?'ended':''}" data-event-countdown="${st==='upcoming'?e.starts_at:e.ends_at}">Đang tính...</div><div class="event-featured-actions"><a class="btn" href="event.html?id=${encodeURIComponent(e.id)}">Xem Event</a><button class="ghost join-event-v272" data-id="${e.id}" ${joined||st!=='live'?'disabled':''}>${joined?'✓ Đã tham gia':st==='live'?'Tham gia miễn phí':st==='upcoming'?'Chưa mở':'Đã kết thúc'}</button></div>`;box.querySelector('.join-event-v272')?.addEventListener('click',e=>join(e.currentTarget))}
async function hidden(){try{return new Set((await rpc('nexora_my_hidden_history_v2687')||[]).map(x=>`${x.history_type}:${x.history_key}`))}catch{return new Set()}}
async function renderHistory(){const box=$('eventMyHistory');if(!box)return;const h=await hidden();const rows=events.filter(e=>entryMap.has(String(e.id))&&!h.has(`event_entry:${e.id}`));box.innerHTML=rows.map(e=>{const x=entryMap.get(String(e.id));return`<div class="event-history-card"><div><b>${safe(e.title)}</b><small>${safe(statusText(x.status))} • ${fmt(x.created_at)}</small></div><button class="ghost small hide-event-v272" data-id="${e.id}">🗑️ Ẩn</button></div>`}).join('')||'<div class="hub-empty">Bạn chưa có lịch sử Event đang hiển thị.</div>';box.querySelectorAll('.hide-event-v272').forEach(b=>b.onclick=async()=>{if(!confirm('Ẩn lượt tham gia Event này khỏi lịch sử của bạn?'))return;try{await rpc('nexora_hide_history_item_v2687',{p_history_type:'event_entry',p_history_key:String(b.dataset.id)});renderHistory()}catch(e){say(e.message,true)}})}
async function join(b){b.disabled=true;try{const d=await rpc('nexora_join_event',{p_event_id:b.dataset.id});say(d?.message||'Đã tham gia Event',!d?.ok);await load()}catch(e){say(e.message,true);b.disabled=false}}
async function loadResults(){resultMap.clear();await Promise.all(events.filter(e=>state(e)==='ended'||e.result_text).map(async e=>{try{resultMap.set(String(e.id),await rpc('nexora_event_public_results_v272',{p_event_id:e.id})||[])}catch{resultMap.set(String(e.id),[])}}))}
async function load(){const er=await db.from('nexora_events').select('*').eq('is_published',true).in('lifecycle_status',['published','ended']).order('starts_at',{ascending:false});if(er.error){say('Hãy chạy SQL v2.7.2 trước: '+er.error.message,true);return}events=er.data||[];const [entriesR,countsR]=await Promise.all([db.from('nexora_event_entries').select('event_id,status,created_at').eq('user_id',user.id),db.rpc('nexora_event_public_counts_v272')]);entryMap=new Map((entriesR.data||[]).map(x=>[String(x.event_id),x]));countMap=new Map((countsR.data||[]).map(x=>[String(x.event_id),Number(x.participants||0)]));await loadResults();render()}
function bindTabs(){document.querySelectorAll('[data-event-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.eventFilter;document.querySelectorAll('[data-event-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$('hubRefresh')?.addEventListener('click',load)}
async function detail(){const id=new URLSearchParams(location.search).get('id');if(!id)return;const r=await db.from('nexora_events').select('*').eq('id',id).eq('is_published',true).in('lifecycle_status',['published','ended']).maybeSingle();const e=r.data;if(!e){$('eventDetailMain').innerHTML='<div class="hub-empty">Không tìm thấy Event hoặc Event chưa được công bố.</div>';return}events=[e];const [entryR,countR,res]=await Promise.all([db.from('nexora_event_entries').select('event_id,status,created_at').eq('user_id',user.id).eq('event_id',id).maybeSingle(),rpc('nexora_event_public_counts_v272'),rpc('nexora_event_public_results_v272',{p_event_id:id})]);if(entryR.data)entryMap.set(String(id),entryR.data);countMap=new Map((countR||[]).map(x=>[String(x.event_id),Number(x.participants||0)]));resultMap.set(String(id),res||[]);const st=state(e),joined=entryMap.has(String(id)),n=countMap.get(String(id))||0,full=e.max_participants&&n>=e.max_participants,can=st==='live'&&!joined&&!full&&e.lifecycle_status==='published';$('eventDetailMain').innerHTML=`<div class="event-detail-layout"><article class="event-detail-card"><div class="event-card-meta"><span class="event-state ${st}">${stateLabel(st)}</span>${e.is_featured?'<span class="hub-badge">⭐ FEATURED</span>':''}</div><h1>${safe(e.title)}</h1><p>${safe(e.description||'')}</p><div class="hub-badge">🎁 ${safe(e.reward_text||'Phần thưởng cộng đồng')}</div><h3>📜 Thể lệ</h3><div class="event-rules-v272">${safe(e.rules||'Theo thông báo của Admin.')}</div>${resultHtml(e)}</article><aside class="event-side-card"><div class="event-side-stat"><span>Bắt đầu</span><b>${fmt(e.starts_at)}</b></div><div class="event-side-stat"><span>Kết thúc</span><b>${fmt(e.ends_at)}</b></div><div class="event-side-stat"><span>Tham gia</span><b>${participantText(e)}</b></div><div class="event-countdown ${st==='ended'?'ended':''}" data-event-countdown="${st==='upcoming'?e.starts_at:e.ends_at}">Đang tính...</div>${progress(e)}<div class="hub-card-actions"><button class="${joined?'ghost':'btn'}" id="eventDetailJoin" data-id="${e.id}" ${can?'':'disabled'}>${joined?'✓ Đã tham gia':full?'Đã đủ người':st==='upcoming'?'Chưa mở':st==='ended'?'Đã kết thúc':'Tham gia miễn phí'}</button><a class="ghost" href="events.html">← Event Center</a></div></aside></div>`;$('eventDetailJoin')?.addEventListener('click',e=>join(e.currentTarget));startTicker()}
async function init(){if(!await auth())return;if(document.body.dataset.eventPage==='detail'){await detail();return}bindTabs();await load()}
document.addEventListener('DOMContentLoaded',init);
})();