(()=>{'use strict';const app=document.getElementById('stageApp'),db=supabase.createClient(NEXORA_CONFIG.SUPABASE_URL,NEXORA_CONFIG.SUPABASE_KEY),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let lastKey='',flashUntil=0;
async function rpc(){const {data,error}=await db.rpc('nexora_live_stage_v2144');if(error)throw error;return data}
const labels={called:'ĐANG CHUẨN BỊ',ready:'ĐÃ SẴN SÀNG',playing:'ĐANG THỬ THÁCH',success:'VƯỢT THỬ THÁCH',failed:'DỪNG CUỘC CHƠI',absent:'VẮNG MẶT',violation:'VI PHẠM LUẬT',queued:'ĐANG CHỜ'};
function rules(s){return String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,6).map(x=>`<li>${esc(x)}</li>`).join('')}
function finalState(ps){return ps.length&&ps.every(p=>['success','failed','absent','violation'].includes(p.status))}
function latest(ps){return Math.max(0,...ps.map(p=>new Date(p.updated_at||0).getTime()))}
function render(d){const c=d?.challenge,ps=d?.players||[],next=d?.next_players||[];if(!c){app.innerHTML=`<section class="stage-card stage-idle"><div class="stage-crown">👑</div><div class="kicker">NEXORA GAMESHOW</div><h1>AI LÀ TRIỆU PHÚ<br><span>FREE FIRE?</span></h1><p>Chương trình chưa bắt đầu</p><div class="stage-wait">ĐANG CHỜ GAMESHOW TIẾP THEO...</div></section>`;return}
const key=`${c.id}:${c.current_round}:${ps.map(p=>p.status).join(',')}:${latest(ps)}`;if(key!==lastKey){lastKey=key;if(finalState(ps))flashUntil=Date.now()+10000}
const finals=finalState(ps),showFinal=finals&&Date.now()<flashUntil,playing=ps.some(p=>p.status==='playing'),called=ps.some(p=>p.status==='called'),ready=ps.length&&ps.every(p=>['ready','playing','success','failed','absent','violation'].includes(p.status));
let state=playing?'🎮 TRẬN ĐẤU ĐANG DIỄN RA':called?'🔥 THÍ SINH ĐANG CHUẨN BỊ':ready?'✅ ĐÃ SẴN SÀNG':'⏳ ĐANG CHỜ LƯỢT TIẾP THEO';
if(showFinal){const wins=ps.filter(p=>p.status==='success'),bad=ps.filter(p=>p.status==='violation'),fail=ps.filter(p=>p.status==='failed'),abs=ps.filter(p=>p.status==='absent');let title=wins.length?'🏆 BOOYAH!':'❌ DỪNG CUỘC CHƠI',sub=wins.length?`${wins.length} thí sinh vượt qua thử thách`:(bad.length?'Có thí sinh vi phạm luật':fail.length?'Thử thách chưa được hoàn thành':abs.length?'Thí sinh vắng mặt':'Đã có kết quả');app.innerHTML=`<section class="stage-card stage-final ${wins.length?'win':'out'}"><div class="stage-crown">${wins.length?'🏆':'👑'}</div><div class="kicker">AI LÀ TRIỆU PHÚ FREE FIRE • LƯỢT #${c.current_round||'—'}</div><h1>${title}</h1><p class="final-sub">${esc(sub)}</p><div class="stage-players final-list">${ps.map(p=>`<div class="stage-player ${p.status}"><strong>${esc(p.display_name||'Game thủ')}</strong><span>${labels[p.status]||esc(p.status)}${p.status==='success'?` • +${p.reward_points||c.reward_points||0} PTS`:''}</span></div>`).join('')}</div><div class="stage-next">Kết quả sẽ tự chuyển về màn hình chờ...</div></section>`;return}
app.innerHTML=`<section class="stage-card"><header><div><div class="kicker">👑 NEXORA GAMESHOW • FREE FIRE</div><h1>AI LÀ TRIỆU PHÚ <span>FREE FIRE?</span></h1></div><div class="live-pill">${c.broadcast_status==='live'?'● LIVESTREAM':c.broadcast_status==='paused'?'Ⅱ TẠM NGHỈ':c.admin_online?'● ADMIN ONLINE':'○ CHỜ'}</div></header><div class="stage-status">${state}</div><div class="stage-main"><section><div class="round">LƯỢT #${c.current_round||'—'}</div><h2>${esc(c.title)}</h2><div class="target"><small>🎯 MỤC TIÊU</small><strong>${esc(c.requirement||'Vượt qua thử thách')}</strong></div><div class="reward"><small>🎁 GIẢI THƯỞNG</small><strong>${Number(c.reward_points||0)} PTS${c.reward_text?' • '+esc(c.reward_text):''}</strong></div><div class="stage-players">${ps.length?ps.map(p=>`<div class="stage-player ${p.status}"><strong>#${p.queue_no} • ${esc(p.display_name||'Game thủ')}</strong><span>${labels[p.status]||esc(p.status)}</span></div>`).join(''):'<div class="no-player">Đang chờ Admin gọi thí sinh...</div>'}</div>${next.length?`<div class="stage-next"><b>⏭️ TIẾP THEO</b><br>${next.map(p=>`#${p.queue_no} ${esc(p.display_name||'Game thủ')}`).join(' • ')}</div>`:''}</section><aside><div class="rules-title">📜 LUẬT THỬ THÁCH</div><ol>${rules(c.rules_text)||'<li>Admin sẽ công bố luật trước khi bắt đầu.</li>'}</ol><div class="one-chance">1 CƠ HỘI • 1 TRẬN RANK<br><b>BOOYAH HOẶC OUT</b></div></aside></div><footer>NEXORA GAMING • MÀN HÌNH SÂN KHẤU TRỰC TIẾP</footer></section>`}
async function load(){try{render(await rpc())}catch(e){app.innerHTML=`<section class="stage-card stage-idle"><div class="stage-crown">⚠️</div><h1>MẤT KẾT NỐI</h1><p>${esc(e.message)}</p><div class="stage-wait">ĐANG THỬ KẾT NỐI LẠI...</div></section>`}}
load();setInterval(load,2500);setInterval(()=>{if(flashUntil&&Date.now()>=flashUntil)load()},1000)})();
