/* Nexora Gaming v1.5.2 — URL Proof Guide
   Proof-only patch. Does not modify Daily System or Achievements. */
(()=>{
  const q=id=>document.getElementById(id);
  const safe=s=>typeof esc==='function'?esc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=s=>typeof fmtDate==='function'?fmtDate(s):new Date(s).toLocaleString('vi-VN');
  const status=s=>typeof proofStatus==='function'?proofStatus(s):({pending:'⏳ Chờ duyệt',approved:'✓ Đã duyệt',rejected:'✕ Từ chối'}[s]||s);
  const validUrl=v=>{try{const u=new URL(v);return u.protocol==='http:'||u.protocol==='https:'}catch{return false}};
  const copy=async text=>{try{await navigator.clipboard.writeText(text);return true}catch{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();const ok=document.execCommand('copy');t.remove();return ok}};
  const guide=()=>`<button type="button" id="proofGuideToggle" class="proof-guide-btn">❓ Hướng dẫn lấy URL ảnh/video</button><div id="proofGuide" class="proof-guide hidden"><h3>📎 Cách tạo URL bằng chứng</h3><ol><li>Tải ảnh hoặc video của bạn lên một dịch vụ lưu trữ/chia sẻ mà bạn sử dụng.</li><li>Bật quyền chia sẻ để <b>người có liên kết có thể xem</b>.</li><li>Chọn <b>Sao chép liên kết / Copy link</b>.</li><li>Quay lại Nexora, dán liên kết vào ô <b>URL bằng chứng</b> rồi gửi Admin duyệt.</li></ol><div class="proof-guide-warning">⚠️ Trước khi gửi, hãy thử mở URL ở tab ẩn danh. Nếu xem được mà không cần đăng nhập thì Admin cũng có thể kiểm tra. Không gửi mật khẩu, OTP, mã khôi phục hoặc thông tin đăng nhập game.</div></div>`;
  const wireGuide=()=>{const b=q('proofGuideToggle'),g=q('proofGuide');if(b&&g)b.onclick=()=>{g.classList.toggle('hidden');b.textContent=g.classList.contains('hidden')?'❓ Hướng dẫn lấy URL ảnh/video':'✕ Đóng hướng dẫn'}};
  const linkBlock=url=>{if(!url)return'<span class="note">Không có URL bằng chứng.</span>';const u=safe(url);return `<a class="proof-url-display" href="${u}" target="_blank" rel="noopener noreferrer" title="${u}">${u}</a><div class="proof-url-actions"><a class="ghost small" href="${u}" target="_blank" rel="noopener noreferrer">Mở bằng chứng ↗</a><button type="button" class="ghost small proof-copy-url" data-url="${u}">Copy URL</button></div>`};
  const wireCopies=()=>document.querySelectorAll('.proof-copy-url').forEach(b=>b.onclick=async()=>{const ok=await copy(b.dataset.url||'');const old=b.textContent;b.textContent=ok?'Đã copy ✓':'Không copy được';setTimeout(()=>b.textContent=old,1300)});

  window.showProofForm=function(type,id,title,points,user){const box=q('proofList');if(!box)return;box.scrollIntoView({behavior:'smooth',block:'center'});box.innerHTML=`<article class="proof-card"><div class="proof-head"><b>🔗 ${safe(title)}</b><strong>+${points} điểm</strong></div>${guide()}<form id="proofSubmitForm" class="proof-form"><label>URL bằng chứng<input id="proofUrl" class="proof-url-input" type="url" inputmode="url" autocomplete="url" maxlength="500" required placeholder="https://..."></label><textarea id="proofNote" maxlength="500" required placeholder="Ghi chú: kết quả trận, số mạng, Top bao nhiêu..."></textarea><div class="proof-actions"><button id="proofSubmitBtn" class="btn">Gửi URL cho Admin duyệt</button><button type="button" id="proofCancel" class="ghost">Hủy</button></div></form></article>`;wireGuide();q('proofCancel').onclick=()=>window.loadProofs(user);q('proofSubmitForm').onsubmit=async e=>{e.preventDefault();const url=q('proofUrl').value.trim();if(!validUrl(url))return msg('dashMsg','URL phải bắt đầu bằng http:// hoặc https://',true);const btn=q('proofSubmitBtn');btn.disabled=true;btn.textContent='Đang gửi...';try{const {data,error}=await db.rpc('nexora_submit_challenge_proof',{p_challenge_type:type,p_challenge_id:id,p_proof_url:url,p_note:q('proofNote').value.trim()});if(error)throw error;if(!data?.ok)return msg('dashMsg',data?.message||'Không thể gửi bằng chứng.',true);msg('dashMsg',data.message||'Đã gửi URL bằng chứng ✓');window.loadProofs(user)}catch(err){msg('dashMsg',err?.message||'Không thể gửi bằng chứng.',true)}finally{btn.disabled=false;btn.textContent='Gửi URL cho Admin duyệt'}}};

  window.loadProofs=async function(user){const box=q('proofList');if(!box)return;const {data,error}=await db.rpc('nexora_my_challenge_proofs');if(error){box.textContent='Không tải được Proof Center. Hãy kiểm tra SQL v1.5.2.';return}box.innerHTML=guide()+((data||[]).map(x=>{const url=x.proof_url||x.url||x.proofUrl||'';return `<article class="proof-card ${safe(x.status)}"><div class="proof-head"><b>${x.challenge_type==='daily'?'🎯 Daily':'🎲 Random'} • ${safe(x.challenge_title)}</b><span class="proof-status">${status(x.status)}</span></div><small>Gửi ${date(x.created_at)} • +${x.points} điểm</small><p>${safe(x.note||'')}</p>${linkBlock(url)}${x.admin_note?`<p class="note">Admin: ${safe(x.admin_note)}</p>`:''}</article>`}).join('')||'<div class="empty-state">Chưa gửi bằng chứng Challenge nào.</div>');wireGuide();wireCopies()};

  window.adminProofs=async function(){const box=q('adminProofList');if(!box)return;async function load(){const {data,error}=await db.rpc('nexora_admin_challenge_proofs',{p_status:'pending'});if(error){box.textContent='Không tải được danh sách Proof. Hãy kiểm tra SQL v1.5.2.';return}box.innerHTML=(data||[]).map(x=>{const url=x.proof_url||x.url||x.proofUrl||'';return `<article class="proof-card pending"><div class="proof-head"><b>${safe(x.display_name)} • ${safe(x.challenge_title)}</b><strong>+${x.points} điểm</strong></div><small>${x.challenge_type==='daily'?'Daily':'Random'} • ${date(x.created_at)} • UID: ${safe(x.game_uid||'chưa có')}</small><p>${safe(x.note||'')}</p>${linkBlock(url)}<div class="proof-actions"><button class="btn proof-review-v152" data-id="${safe(x.submission_id)}" data-status="approved">✓ Duyệt + cộng điểm</button><button class="ghost proof-review-v152" data-id="${safe(x.submission_id)}" data-status="rejected">Từ chối</button></div></article>`}).join('')||'<div class="empty-state">Không có bằng chứng nào đang chờ duyệt.</div>';wireCopies();document.querySelectorAll('.proof-review-v152').forEach(b=>b.onclick=async()=>{let note='';if(b.dataset.status==='rejected')note=prompt('Lý do từ chối (không bắt buộc):')||'';const {data,error}=await db.rpc('nexora_admin_review_challenge_proof',{p_submission_id:b.dataset.id,p_status:b.dataset.status,p_admin_note:note});if(error)return msg('adminMsg',error.message,true);msg('adminMsg',data?.message||'Đã xử lý',!data?.ok);load()})}if(q('refreshProofAdmin'))q('refreshProofAdmin').onclick=load;await load()};

  // Refresh only Proof UI after the original app has initialized.
  setTimeout(async()=>{try{const {data:{user}}=await db.auth.getUser();if(user&&q('proofList')){if(q('refreshProofs'))q('refreshProofs').onclick=()=>window.loadProofs(user);window.loadProofs(user)}if(q('adminProofList'))window.adminProofs()}catch(e){console.warn('v1.5.2 proof patch:',e)}},0);
})();
